// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_settings.sql

package db

import (
	"context"
)

const getAppSetting = `-- name: GetAppSetting :one
SELECT value FROM app_settings WHERE key = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getAppSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setAppSetting = `-- name: SetAppSetting :exec
INSERT INTO app_settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type SetAppSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetAppSetting(ctx context.Context, arg *SetAppSettingParams) error {
	_, err := q.db.Exec(ctx, setAppSetting, arg.Key, arg.Value)
	return err
}
