// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, color, created_at
`

type CreateCategoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Color  string      `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg *CreateCategoryParams) (*Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.UserID, arg.Name, arg.Color)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg *DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, name, color, created_at FROM categories WHERE id = $1 AND user_id = $2
`

type GetCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg *GetCategoryParams) (*Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, name, color, created_at FROM categories WHERE user_id = $1 ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context, userID pgtype.UUID) ([]*Category, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $3, color = $4
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, color, created_at
`

type UpdateCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Color  string      `json:"color"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg *UpdateCategoryParams) (*Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}
