// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TodoStatus string

const (
	TodoStatusActive  TodoStatus = "active"
	TodoStatusSnoozed TodoStatus = "snoozed"
	TodoStatusDone    TodoStatus = "done"
)

func (e *TodoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoStatus(s)
	case string:
		*e = TodoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoStatus: %T", src)
	}
	return nil
}

type NullTodoStatus struct {
	TodoStatus TodoStatus `json:"todo_status"`
	Valid      bool       `json:"valid"` // Valid is true if TodoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TodoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoStatus), nil
}

type AppSetting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PushSubscription struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Endpoint  string             `json:"endpoint"`
	P256dh    string             `json:"p256dh"`
	Auth      string             `json:"auth"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Todo struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Deadline          pgtype.Date        `json:"deadline"`
	ReminderAt        pgtype.Timestamptz `json:"reminder_at"`
	ReminderJobID     pgtype.Int8        `json:"reminder_job_id"`
	Priority          int16              `json:"priority"`
	Status            TodoStatus         `json:"status"`
	SnoozeUntil       pgtype.Date        `json:"snooze_until"`
	DoneAt            pgtype.Timestamptz `json:"done_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DurationMinutes   pgtype.Int4        `json:"duration_minutes"`
	Subtasks          []byte             `json:"subtasks"`
	RecurrenceRule    pgtype.Text        `json:"recurrence_rule"`
	RecurrenceEndDate pgtype.Date        `json:"recurrence_end_date"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Timezone     string             `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Role         string             `json:"role"`
	OidcSubject  pgtype.Text        `json:"oidc_subject"`
}
