// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TodoStatus string

const (
	TodoStatusActive  TodoStatus = "active"
	TodoStatusSnoozed TodoStatus = "snoozed"
	TodoStatusDone    TodoStatus = "done"
)

func (e *TodoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoStatus(s)
	case string:
		*e = TodoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoStatus: %T", src)
	}
	return nil
}

type NullTodoStatus struct {
	TodoStatus TodoStatus
	Valid      bool // Valid is true if TodoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TodoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoStatus), nil
}

type AppSetting struct {
	Key   string
	Value string
}

type Category struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Color     string
	CreatedAt pgtype.Timestamptz
}

type PushSubscription struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Endpoint  string
	P256dh    string
	Auth      string
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Todo struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	CategoryID        pgtype.UUID
	Title             string
	Description       pgtype.Text
	Deadline          pgtype.Date
	ReminderAt        pgtype.Timestamptz
	ReminderJobID     pgtype.Int8
	Priority          int16
	Status            TodoStatus
	SnoozeUntil       pgtype.Date
	DoneAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DurationMinutes   pgtype.Int4
	Subtasks          []byte
	RecurrenceRule    pgtype.Text
	RecurrenceEndDate pgtype.Date
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	Timezone     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Role         string
}
