// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE endpoint = $1 AND user_id = $2
`

type DeletePushSubscriptionParams struct {
	Endpoint string
	UserID   pgtype.UUID
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg *DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.Endpoint, arg.UserID)
	return err
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, created_at FROM push_subscriptions WHERE user_id = $1
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID pgtype.UUID) ([]*PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint) DO UPDATE
    SET p256dh = EXCLUDED.p256dh,
        auth   = EXCLUDED.auth,
        user_id = EXCLUDED.user_id
RETURNING id, user_id, endpoint, p256dh, auth, created_at
`

type UpsertPushSubscriptionParams struct {
	UserID   pgtype.UUID
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg *UpsertPushSubscriptionParams) (*PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
	)
	return &i, err
}
