// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (user_id, category_id, title, description, deadline, reminder_at, priority, duration_minutes, subtasks, recurrence_rule, recurrence_end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date
`

type CreateTodoParams struct {
	UserID            pgtype.UUID
	CategoryID        pgtype.UUID
	Title             string
	Description       pgtype.Text
	Deadline          pgtype.Date
	ReminderAt        pgtype.Timestamptz
	Priority          int16
	DurationMinutes   pgtype.Int4
	Subtasks          []byte
	RecurrenceRule    pgtype.Text
	RecurrenceEndDate pgtype.Date
}

func (q *Queries) CreateTodo(ctx context.Context, arg *CreateTodoParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.UserID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Deadline,
		arg.ReminderAt,
		arg.Priority,
		arg.DurationMinutes,
		arg.Subtasks,
		arg.RecurrenceRule,
		arg.RecurrenceEndDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.ReminderAt,
		&i.ReminderJobID,
		&i.Priority,
		&i.Status,
		&i.SnoozeUntil,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationMinutes,
		&i.Subtasks,
		&i.RecurrenceRule,
		&i.RecurrenceEndDate,
	)
	return &i, err
}

const createTodoFromRecurrence = `-- name: CreateTodoFromRecurrence :one
INSERT INTO todos (user_id, category_id, title, description, deadline, reminder_at, priority, duration_minutes, subtasks, recurrence_rule, recurrence_end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date
`

type CreateTodoFromRecurrenceParams struct {
	UserID            pgtype.UUID
	CategoryID        pgtype.UUID
	Title             string
	Description       pgtype.Text
	Deadline          pgtype.Date
	ReminderAt        pgtype.Timestamptz
	Priority          int16
	DurationMinutes   pgtype.Int4
	Subtasks          []byte
	RecurrenceRule    pgtype.Text
	RecurrenceEndDate pgtype.Date
}

func (q *Queries) CreateTodoFromRecurrence(ctx context.Context, arg *CreateTodoFromRecurrenceParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, createTodoFromRecurrence,
		arg.UserID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Deadline,
		arg.ReminderAt,
		arg.Priority,
		arg.DurationMinutes,
		arg.Subtasks,
		arg.RecurrenceRule,
		arg.RecurrenceEndDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.ReminderAt,
		&i.ReminderJobID,
		&i.Priority,
		&i.Status,
		&i.SnoozeUntil,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationMinutes,
		&i.Subtasks,
		&i.RecurrenceRule,
		&i.RecurrenceEndDate,
	)
	return &i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1 AND user_id = $2
`

type DeleteTodoParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteTodo(ctx context.Context, arg *DeleteTodoParams) error {
	_, err := q.db.Exec(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date FROM todos WHERE id = $1 AND user_id = $2
`

type GetTodoParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetTodo(ctx context.Context, arg *GetTodoParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.ReminderAt,
		&i.ReminderJobID,
		&i.Priority,
		&i.Status,
		&i.SnoozeUntil,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationMinutes,
		&i.Subtasks,
		&i.RecurrenceRule,
		&i.RecurrenceEndDate,
	)
	return &i, err
}

const getTodosWithDueReminder = `-- name: GetTodosWithDueReminder :many
SELECT id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date FROM todos
WHERE reminder_at IS NOT NULL
  AND reminder_at <= NOW()
  AND status != 'done'
`

func (q *Queries) GetTodosWithDueReminder(ctx context.Context) ([]*Todo, error) {
	rows, err := q.db.Query(ctx, getTodosWithDueReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.ReminderAt,
			&i.ReminderJobID,
			&i.Priority,
			&i.Status,
			&i.SnoozeUntil,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Subtasks,
			&i.RecurrenceRule,
			&i.RecurrenceEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByCategory = `-- name: ListTodosByCategory :many
SELECT id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date FROM todos
WHERE user_id = $1
  AND category_id = $2
  AND status != 'done'
ORDER BY deadline ASC, priority DESC, created_at ASC
`

type ListTodosByCategoryParams struct {
	UserID     pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) ListTodosByCategory(ctx context.Context, arg *ListTodosByCategoryParams) ([]*Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByCategory, arg.UserID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.ReminderAt,
			&i.ReminderJobID,
			&i.Priority,
			&i.Status,
			&i.SnoozeUntil,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Subtasks,
			&i.RecurrenceRule,
			&i.RecurrenceEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosDone = `-- name: ListTodosDone :many
SELECT id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date FROM todos
WHERE user_id = $1
  AND status = 'done'
ORDER BY done_at DESC
`

func (q *Queries) ListTodosDone(ctx context.Context, userID pgtype.UUID) ([]*Todo, error) {
	rows, err := q.db.Query(ctx, listTodosDone, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.ReminderAt,
			&i.ReminderJobID,
			&i.Priority,
			&i.Status,
			&i.SnoozeUntil,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Subtasks,
			&i.RecurrenceRule,
			&i.RecurrenceEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosOverdue = `-- name: ListTodosOverdue :many
SELECT id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date FROM todos
WHERE user_id = $1
  AND status IN ('active', 'snoozed')
  AND deadline < (CURRENT_DATE AT TIME ZONE ($2::text))::date
ORDER BY deadline ASC, priority DESC, created_at ASC
`

type ListTodosOverdueParams struct {
	UserID   pgtype.UUID
	Timezone string
}

func (q *Queries) ListTodosOverdue(ctx context.Context, arg *ListTodosOverdueParams) ([]*Todo, error) {
	rows, err := q.db.Query(ctx, listTodosOverdue, arg.UserID, arg.Timezone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.ReminderAt,
			&i.ReminderJobID,
			&i.Priority,
			&i.Status,
			&i.SnoozeUntil,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Subtasks,
			&i.RecurrenceRule,
			&i.RecurrenceEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosToday = `-- name: ListTodosToday :many
SELECT id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date FROM todos
WHERE user_id = $1
  AND status = 'active'
  AND deadline = (CURRENT_DATE AT TIME ZONE ($2::text))::date
ORDER BY priority DESC, deadline ASC, created_at ASC
`

type ListTodosTodayParams struct {
	UserID   pgtype.UUID
	Timezone string
}

func (q *Queries) ListTodosToday(ctx context.Context, arg *ListTodosTodayParams) ([]*Todo, error) {
	rows, err := q.db.Query(ctx, listTodosToday, arg.UserID, arg.Timezone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.ReminderAt,
			&i.ReminderJobID,
			&i.Priority,
			&i.Status,
			&i.SnoozeUntil,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Subtasks,
			&i.RecurrenceRule,
			&i.RecurrenceEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosUpcoming = `-- name: ListTodosUpcoming :many
SELECT id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date FROM todos
WHERE user_id = $1
  AND status = 'active'
  AND deadline > (CURRENT_DATE AT TIME ZONE ($2::text))::date
ORDER BY deadline ASC, priority DESC, created_at ASC
`

type ListTodosUpcomingParams struct {
	UserID   pgtype.UUID
	Timezone string
}

func (q *Queries) ListTodosUpcoming(ctx context.Context, arg *ListTodosUpcomingParams) ([]*Todo, error) {
	rows, err := q.db.Query(ctx, listTodosUpcoming, arg.UserID, arg.Timezone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Deadline,
			&i.ReminderAt,
			&i.ReminderJobID,
			&i.Priority,
			&i.Status,
			&i.SnoozeUntil,
			&i.DoneAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMinutes,
			&i.Subtasks,
			&i.RecurrenceRule,
			&i.RecurrenceEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenTodo = `-- name: ReopenTodo :one
UPDATE todos SET status = 'active', done_at = NULL, snooze_until = NULL, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date
`

type ReopenTodoParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ReopenTodo(ctx context.Context, arg *ReopenTodoParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, reopenTodo, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.ReminderAt,
		&i.ReminderJobID,
		&i.Priority,
		&i.Status,
		&i.SnoozeUntil,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationMinutes,
		&i.Subtasks,
		&i.RecurrenceRule,
		&i.RecurrenceEndDate,
	)
	return &i, err
}

const setTodoDone = `-- name: SetTodoDone :one
UPDATE todos SET status = 'done', done_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date
`

type SetTodoDoneParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SetTodoDone(ctx context.Context, arg *SetTodoDoneParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, setTodoDone, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.ReminderAt,
		&i.ReminderJobID,
		&i.Priority,
		&i.Status,
		&i.SnoozeUntil,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationMinutes,
		&i.Subtasks,
		&i.RecurrenceRule,
		&i.RecurrenceEndDate,
	)
	return &i, err
}

const snoozeTodo = `-- name: SnoozeTodo :one
UPDATE todos SET deadline = $3, snooze_until = NULL, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date
`

type SnoozeTodoParams struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Deadline pgtype.Date
}

func (q *Queries) SnoozeTodo(ctx context.Context, arg *SnoozeTodoParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, snoozeTodo, arg.ID, arg.UserID, arg.Deadline)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.ReminderAt,
		&i.ReminderJobID,
		&i.Priority,
		&i.Status,
		&i.SnoozeUntil,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationMinutes,
		&i.Subtasks,
		&i.RecurrenceRule,
		&i.RecurrenceEndDate,
	)
	return &i, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET category_id      = $3,
    title            = $4,
    description      = $5,
    deadline         = $6,
    reminder_at      = $7,
    reminder_job_id  = $8,
    priority         = $9,
    duration_minutes = $10,
    subtasks         = $11,
    recurrence_rule  = $12,
    recurrence_end_date = $13,
    updated_at       = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, title, description, deadline, reminder_at, reminder_job_id, priority, status, snooze_until, done_at, created_at, updated_at, duration_minutes, subtasks, recurrence_rule, recurrence_end_date
`

type UpdateTodoParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	CategoryID        pgtype.UUID
	Title             string
	Description       pgtype.Text
	Deadline          pgtype.Date
	ReminderAt        pgtype.Timestamptz
	ReminderJobID     pgtype.Int8
	Priority          int16
	DurationMinutes   pgtype.Int4
	Subtasks          []byte
	RecurrenceRule    pgtype.Text
	RecurrenceEndDate pgtype.Date
}

func (q *Queries) UpdateTodo(ctx context.Context, arg *UpdateTodoParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Deadline,
		arg.ReminderAt,
		arg.ReminderJobID,
		arg.Priority,
		arg.DurationMinutes,
		arg.Subtasks,
		arg.RecurrenceRule,
		arg.RecurrenceEndDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Deadline,
		&i.ReminderAt,
		&i.ReminderJobID,
		&i.Priority,
		&i.Status,
		&i.SnoozeUntil,
		&i.DoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationMinutes,
		&i.Subtasks,
		&i.RecurrenceRule,
		&i.RecurrenceEndDate,
	)
	return &i, err
}
