// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
	Timezone     string
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, timezone, created_at, updated_at, role FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, timezone, created_at, updated_at, role FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return &i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role
`

type SetUserRoleParams struct {
	ID   pgtype.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg *SetUserRoleParams) (*User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return &i, err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :one
UPDATE users SET timezone = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role
`

type UpdateUserTimezoneParams struct {
	ID       pgtype.UUID
	Timezone string
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg *UpdateUserTimezoneParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserTimezone, arg.ID, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return &i, err
}
