// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOIDCUser = `-- name: CreateOIDCUser :one
INSERT INTO users (email, password_hash, name, timezone, oidc_subject)
VALUES ($1, '', $2, $3, $4)
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject
`

type CreateOIDCUserParams struct {
	Email       string      `json:"email"`
	Name        string      `json:"name"`
	Timezone    string      `json:"timezone"`
	OidcSubject pgtype.Text `json:"oidc_subject"`
}

func (q *Queries) CreateOIDCUser(ctx context.Context, arg *CreateOIDCUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createOIDCUser,
		arg.Email,
		arg.Name,
		arg.Timezone,
		arg.OidcSubject,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Timezone     string `json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}

const getUserByOIDCSubject = `-- name: GetUserByOIDCSubject :one
SELECT id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject
FROM users WHERE oidc_subject = $1
`

func (q *Queries) GetUserByOIDCSubject(ctx context.Context, oidcSubject pgtype.Text) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSubject, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}

const linkOIDCSubject = `-- name: LinkOIDCSubject :one
UPDATE users SET oidc_subject = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject
`

type LinkOIDCSubjectParams struct {
	ID          pgtype.UUID `json:"id"`
	OidcSubject pgtype.Text `json:"oidc_subject"`
}

func (q *Queries) LinkOIDCSubject(ctx context.Context, arg *LinkOIDCSubjectParams) (*User, error) {
	row := q.db.QueryRow(ctx, linkOIDCSubject, arg.ID, arg.OidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.OidcSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject
`

type SetUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg *SetUserRoleParams) (*User, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg *UpdateUserRoleParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :one
UPDATE users SET timezone = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, timezone, created_at, updated_at, role, oidc_subject
`

type UpdateUserTimezoneParams struct {
	ID       pgtype.UUID `json:"id"`
	Timezone string      `json:"timezone"`
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, arg *UpdateUserTimezoneParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserTimezone, arg.ID, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.OidcSubject,
	)
	return &i, err
}
